-- VHDL Entity MIPS.MIPS_tb.symbol
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--


ENTITY MIPS_tb IS
-- Declarations

END MIPS_tb ;

--
-- VHDL Architecture MIPS.MIPS_tb.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

LIBRARY work;

ARCHITECTURE struct OF MIPS_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   
   SIGNAL clock           : STD_LOGIC;
   SIGNAL reset           : STD_LOGIC;
   SIGNAL interruptCounter_out :  STD_LOGIC;
   SIGNAL ALU_result_out	:  	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
   SIGNAL outputCount_out :  STD_LOGIC_VECTOR( 31 DOWNTO 0 );
   SIGNAL outputCount_out1 :  STD_LOGIC_VECTOR( 31 DOWNTO 0 );

   -- Component Declarations
   COMPONENT MIPS
   PORT (
      clock           : IN     STD_LOGIC;
      reset           : IN     STD_LOGIC;
	  interruptCounter_out : out std_logic;
	  outputCount_out : out 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
	  outputCount_out1 : out 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
	  ALU_result_out	: out 	STD_LOGIC_VECTOR( 31 DOWNTO 0 )
   );
   END COMPONENT;
   COMPONENT MIPS_tester
   PORT (
      clock           : OUT    STD_LOGIC ;
      reset           : OUT    STD_LOGIC;
	  interruptCounter_out : in STD_LOGIC;
	  outputCount_out : in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
	  outputCount_out1 : in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 );
	  ALU_result_out	: in 	STD_LOGIC_VECTOR( 31 DOWNTO 0 )
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : MIPS USE ENTITY work.mips;
   FOR ALL : MIPS_tester USE ENTITY work.mips_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : MIPS
      PORT MAP (
         reset           => reset,
         clock           => clock,
		 outputCount_out => outputCount_out,
		 outputCount_out1 => outputCount_out1,
		 interruptCounter_out=>interruptCounter_out,
		 ALU_result_out=>ALU_result_out
      );
   U_1 : MIPS_tester
      PORT MAP (
         clock           => clock,
         reset           => reset,
		 outputCount_out => outputCount_out,
		 outputCount_out1 => outputCount_out1,
		 interruptCounter_out=>interruptCounter_out,
		 ALU_result_out=>ALU_result_out
      );

END struct;
